# Generated by Django 5.0 on 2023-12-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_remove_aboutme_photo_url_aboutme_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.TextField(),
        ),
    ]
